before_script:
  - pip install numpy matplotlib nose

stages:
  - test

nosetests:
  stage: test
  script:
    - nosetests -sv --with-coverage

sphinxdoc:
  stage: test
  script:
    - cd doc; make html
