stages:
  - test

ubuntu-tests:
  stage: test
  script:
    - virtualenv pytransform_env
    - source pytransform_env/bin/activate
    - pip install numpy nose coverage sphinx matplotlib
    - nosetests -sv --with-coverage
    - cd doc; make html
  tags:
    - ubuntu14.04

windows-tests:
  stage: test
  script:  # We don't set up any environment here, because we have anaconda
    - nosetests -sv --with-coverage
    - cd doc
    - make.bat html
  tags:
    - windows-server-2008
