stages:
  - test

ubuntu-tests:
  stage: test
  script:
    - virtualenv pytransform_env
    - source pytransform_env/bin/activate
    - pip install numpy scipy nose coverage sphinx matplotlib
    - nosetests -sv --with-coverage
    - cd doc; make html
  tags:
    - ubuntu14.04


# We don't set up any environment on windows machines, because we have
# anaconda and we assume that 'coverage' is installed

windows-python2-tests:
  stage: test
  script:
    - nosetests -sv --with-coverage
    - cd doc
    - make.bat html
  tags:
    - windows-server-2008,python2.7

windows-python3-tests:
  stage: test
  script:
    - nosetests -sv --with-coverage
    - cd doc
    - make.bat html
  tags:
    - windows-server-2008,python3.5
