before_script:
  - virtualenv pytransform_env
  - source pytransform_env/bin/activate
  - pip install numpy nose coverage sphinx matplotlib

stages:
  - test

nosetests:
  stage: test
  script:
    - nosetests -sv --with-coverage
    - cd doc; make html
