language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
branches:
  only:
    - master
    - /\d+\.\d+\..+/
install:
  - pip install numpy scipy lxml bs4 matplotlib coverage
script: "nosetests -sv ."
notifications:
  recipients:
    - alexander.fabisch@dfki.de
  email:
    on_success: change
    on_failure: always
