language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
branches:
  only:
    - master
    - /\d+\.\d+\..+/
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblapack-dev libopenblas-dev
  - pip install --upgrade pip
  - pip install --upgrade numpy scipy lxml bs4 matplotlib coverage
  - python -c "import numpy;print(numpy.__version__)"
  - python -c "import scipy; print(scipy.__version__)"
script: "nosetests -sv ."
notifications:
  recipients:
    - alexander.fabisch@dfki.de
  email:
    on_success: change
    on_failure: always
