language: python
branches:
  only:
    - master
    - /\d+\.\d+\..+/
install:
  - sudo pip install -r requirements.txt
script: nosetests -sv .
notifications:
  recipients:
    - alexander.fabisch@dfki.de
  email:
    on_success: change
    on_failure: always
